import { db } from "@/lib/db";
import { generateNumber } from "@/lib/accounting/api";
import { round2 } from "@/lib/money";
import { appendEvent } from "./event-log";
import { runExtraction } from "@/lib/ocr";

// ===== معالجات المهام =====
//
// كل معالج: يستقبل payload، ينفّذ العمل، ويعيد نتيجة قابلة للتسجيل.
// المعالج يجب أن يكون آمنًا لإعادة التنفيذ (idempotent) لأن إعادة المحاولة
// تعيد استدعاءه على نفس البيانات.

export type JobHandler = (payload: Record<string, unknown>) => Promise<unknown>;

const handlers: Record<string, JobHandler> = {};

// ---------------------------------------------------------------- الاستحقاقات

/** ينشئ المهام المتكرّرة لكل التزام ضريبي قادم (تحضير ) */
handlers["obligation.prepare_tasks"] = async (payload) => {
  const obligationId = String(payload.obligationId ?? "");
  if (!obligationId) throw new Error("obligationId مطلوب");

  const obligation = await db.taxObligation.findUnique({
    where: { id: obligationId },
    include: { company: { select: { id: true, nameAr: true } } },
  });
  if (!obligation) throw new Error("الالتزام غير موجود");

  const due = new Date(obligation.dueDate);
  // نبدأ قبل الموعد بأسبوعين
  const start = new Date(due.getTime() - 14 * 86400000);

  const TEMPLATE = {
    title: `تجهيز «${obligation.title}» لـ ${obligation.company?.nameAr ?? "العميل"}`,
    category: "TAX",
    priority: "URGENT",
  };

  const task = await db.officeTask.create({
    data: {
      taskNumber: await generateNumber("TASK"),
      title: TEMPLATE.title,
      description: `مهمة آلية مولّدة تلقائيًا للالتزام رقم ${obligationId}. تاريخ الاستحقاق ${due.toLocaleDateString("ar-EG")}.`,
      companyId: obligation.companyId,
      obligationId,
      dueDate: start,
      status: "TODO",
      category: TEMPLATE.category,
      priority: TEMPLATE.priority,
    },
  });

  await appendEvent({
    action: "task.auto_created",
    entity: "OfficeTask",
    entityId: task.id,
    actorType: "automation",
    actor: "rule:obligation.prepare_tasks",
    summary: `توليد مهمة تلقائيًا للالتزام: ${obligation.title}`,
    payload: { obligationId, taskId: task.id },
  });

  return { taskId: task.id, taskNumber: task.taskNumber };
};

/** يولّد قائمة المهام القياسية لملف جديد من قوالب الخدمات */
handlers["engagement.generate_checklist"] = async (payload) => {
  const engagementId = String(payload.engagementId ?? "");
  if (!engagementId) throw new Error("engagementId مطلوب");

  const engagement = await db.engagement.findUnique({
    where: { id: engagementId },
    include: { service: { select: { code: true, slaDays: true, name: true } } },
  });
  if (!engagement) throw new Error("ملف العمل غير موجود");

  const templates = await db.taskTemplate.findMany({
    where: {
      isActive: true,
      OR: [{ serviceCode: null }, { serviceCode: engagement.service.code }],
    },
    orderBy: { offsetDays: "asc" },
  });

  if (!templates.length) return { created: 0, note: "لا توجد قوالب مطابقة" };

  const start = engagement.startDate ?? new Date(engagement.createdAt);

  const created: string[] = [];
  let skipped = 0;

  for (const tpl of templates) {
    // مفتاح التكرار هنا هو (ملف + كود القالب): إعادة تشغيل المعالج لا تُنشئ نسخًا
    const existing = await db.officeTask.findFirst({
      where: { engagementId, templateCode: tpl.code },
      select: { id: true },
    });
    if (existing) {
      skipped += 1;
      continue;
    }

    const lead = await db.engagementMember.findFirst({
      where: { engagementId, role: "LEAD" },
      select: { userId: true },
    });

    const task = await db.officeTask.create({
      data: {
        taskNumber: await generateNumber("TASK"),
        title: tpl.title,
        description: tpl.description,
        companyId: engagement.clientId,
        engagementId,
        templateCode: tpl.code,
        autoGenerated: true,
        assignedTo: lead?.userId ?? null,
        dueDate: new Date(start.getTime() + tpl.offsetDays * 86400000),
        category: tpl.category,
        priority: tpl.priority,
        status: "TODO",
      },
    });
    created.push(task.id);
  }

  await appendEvent({
    action: "engagement.checklist_generated",
    entity: "Engagement",
    entityId: engagementId,
    actorType: "automation",
    actor: "rule:engagement.checklist",
    summary: `توليد ${created.length} مهمة من القوالب لملف ${engagement.title}`,
    payload: { count: created.length },
  });

  return { created: created.length, skipped, tasks: created };
};

// ---------------------------------------------------------------- التنبيهات

/** يفحص المهام المتأخرة ويُنشئ تنبيهًا لكل منها مرة واحدة فقط */
handlers["sla.scan_breaches"] = async () => {
  const now = new Date();
  const stale = new Date(now.getTime() - 60 * 60 * 1000);

  const overdue = await db.officeTask.findMany({
    where: {
      dueDate: { lt: now },
      status: { in: ["TODO", "IN_PROGRESS", "REVIEW"] },
      updatedAt: { lt: stale }, // لا نكرر التنبيه ما دامت لم تتغيّر الحالة
    },
    select: { id: true, title: true, dueDate: true, assignedTo: true },
    take: 100,
  });

  let notified = 0;
  for (const task of overdue) {
    const days = Math.floor((now.getTime() - new Date(task.dueDate).getTime()) / 86400000);
    await db.notification.create({
      data: {
        userId: task.assignedTo,
        kind: "SLA_BREACH",
        severity: days > 3 ? "critical" : "warning",
        title: `مهمة متأخرة ${days} يوم: ${task.title}`,
        body: `تجاوزت موعد الإنجاز بمقدار ${days} يوم.`,
        link: "/tasks",
      },
    });
    notified += 1;
  }

  return { scanned: overdue.length, notified };
};

/** ينبّه عند استحقاق ضريبي قادم خلال 7 أيام */
handlers["deadline.scan_upcoming"] = async () => {
  const now = new Date();
  const horizon = new Date(now.getTime() + 7 * 86400000);

  const upcoming = await db.taxObligation.findMany({
    where: { dueDate: { gte: now, lte: horizon }, status: { in: ["PENDING", "IN_PROGRESS"] } },
    include: { company: { select: { nameAr: true } } },
    take: 100,
  });

  let notified = 0;
  for (const o of upcoming) {
    await db.notification.create({
      data: {
        role: "accountant",
        kind: "DEADLINE",
        severity: "warning",
        title: `استحقاق خلال 7 أيام: ${o.title}`,
        body: `شركة ${o.company?.nameAr ?? "—"} — الاستحقاق ${new Date(o.dueDate).toLocaleDateString("ar-EG")}`,
        link: "/obligations",
      },
    });
    notified += 1;
  }

  return { scanned: upcoming.length, notified };
};

// ---------------------------------------------------------------- المحاسبة

/** يتحقق من توازن ميزان المراجعة ويُنبّه إن كان غير متوازن */
handlers["ledger.verify_trial_balance"] = async () => {
  const { getTrialBalance } = await import("@/lib/accounting/ledger");
  const trial = await getTrialBalance({});

  if (trial.balanced) return { balanced: true, difference: 0 };

  await db.notification.create({
    data: {
      role: "admin",
      kind: "JOB_FAILED",
      severity: "critical",
      title: "ميزان المراجعة غير متوازن",
      body: `الفرق ${round2(trial.totalDebit - trial.totalCredit)} — يجب مراجعة القيود قبل إقفال الفترة.`,
      link: "/reports",
    },
  });

  await appendEvent({
    action: "UNBALANCED",
    entity: "Ledger",
    entityId: "trial_balance",
    actorType: "system",
    summary: `ميزان المراجعة غير متوازن بفرق ${round2(trial.totalDebit - trial.totalCredit)}`,
    payload: { debit: trial.totalDebit, credit: trial.totalCredit },
  });

  return { balanced: false, difference: round2(trial.totalDebit - trial.totalCredit) };
};

/** يتحقق من سلامة سلسلة سجل الأحداث — كشف أي تلاعب */
handlers["audit.verify_chain"] = async () => {
  const { verifyChain } = await import("./event-log");
  const result = await verifyChain();
  if (!result.ok) {
    await db.notification.create({
      data: {
        role: "admin",
        kind: "JOB_FAILED",
        severity: "critical",
        title: `سجل الأحداث مكسور (${result.breaks.length} موضع)`,
        body: result.breaks[0]?.reason ?? "تم اكتشاف عبث في السجل",
      },
    });
  }
  return result;
};

export function getHandler(type: string): JobHandler | undefined {
  return handlers[type];
}

export function registeredJobTypes() {
  return Object.keys(handlers);
}

// ---------------------------------------------------------------- الاستخراج الآلي

/** يستخرج بيانات وثيقة مرفوعة عبر نموذج بصري محلي */
handlers["document.extract"] = async (payload) => {
  const documentId = String(payload.documentId ?? "");
  if (!documentId) throw new Error("documentId مطلوب");
  return runExtraction(documentId, {
    provider: payload.provider ? String(payload.provider) : undefined,
    model: payload.model ? String(payload.model) : undefined,
  });
};
