"use client";

// ===== شاشة ملفات العمل (إدارة الممارسة) =====
// ملف العمل = عميل × خدمة × فترة مالية. عند الإنشاء تُطلق قاعدة الأتمتة
// engagement.checklist فتولّد المهام من قوالب الخدمة. اللوح يراقب الملفات
// الحديثة التي لم تولد مهامها بعد (الطابور لم يعمل بعد) فيشغّل دورة حتى
// تكتمل — نفس نمط «الالتزام الذاتي» في بقية الشاشات.

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Briefcase, CheckCircle2, Eye, Loader2, Plus, Trash2, UserRound, X, XCircle } from "lucide-react";
import { apiFetch } from "@/lib/client-api";
import { ENGAGEMENT_STATUS_LABELS, MEMBER_ROLE_LABELS, MONTHS } from "@/lib/domain";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

export interface BoardEngagement {
  id: string;
  code: string;
  title: string;
  status: string;
  periodYear: number;
  periodMonth: number | null;
  clientId: string;
  clientName: string | null;
  service: { id: string; name: string; code: string; slaDays: number; defaultFee: number };
  feeAmount: number;
  currency: string;
  startDate: string | null;
  dueDate: string | null;
  closedAt: string | null;
  members: { userId: string; name: string; role: string; allocationPct: number }[];
  tasksTotal: number;
  tasksDone: number;
  createdAt: string;
}

interface MemberRow {
  userId: string;
  role: "LEAD" | "REVIEWER" | "MEMBER";
  allocationPct: string;
}

const STATUS_VARIANT: Record<string, "default" | "secondary" | "success" | "warning" | "destructive" | "info" | "muted"> = {
  PLANNING: "secondary",
  ACTIVE: "success",
  ON_HOLD: "warning",
  CLOSED: "muted",
};

const ROLE_VARIANT: Record<string, "info" | "warning" | "muted"> = {
  LEAD: "info",
  REVIEWER: "warning",
  MEMBER: "muted",
};

function periodLabel(year: number, month: number | null): string {
  return month ? `${MONTHS[month - 1] ?? month}/${year}` : `سنة ${year}`;
}

function daysUntil(iso: string | null): number | null {
  if (!iso) return null;
  return Math.ceil((new Date(iso).getTime() - Date.now()) / 86400000);
}

function initials(name: string): string {
  return name
    .split(/\s+/)
    .slice(0, 2)
    .map((p) => p[0] ?? "")
    .join("");
}

interface DetailTask {
  id: string;
  title: string;
  status: string;
  priority: string;
  dueDate: string;
  autoGenerated: boolean;
  assignedToUser: { id: string; name: string } | null;
}

interface DetailData {
  code: string;
  title: string;
  status: string;
  notes: string | null;
  dueDate: string | null;
  client: { nameAr: string } | null;
  service: { name: string; slaDays: number };
  members: { name: string; role: string; allocationPct: number }[];
  tasks: DetailTask[];
  documents: { title: string; status: string }[];
}

// الشكل الخام من /api/engagements/[id] (علاقات Prisma غير مفككة)
interface RawDetail {
  code: string;
  title: string;
  status: string;
  notes: string | null;
  dueDate: string | null;
  client: { nameAr: string } | null;
  service: { name: string; slaDays: number };
  members: { role: string; allocationPct: number; user: { name: string } }[];
  tasks: DetailTask[];
  documents: { title: string; status: string }[];
}

// الشكل الخام كما يرجعه /api/engagements (صف Prisma) — قبل التحويل لشكل اللوح
interface RawEngagement {
  id: string;
  code: string;
  title: string;
  status: string;
  periodYear: number;
  periodMonth: number | null;
  clientId: string;
  currency: string;
  feeAmount: number;
  startDate: string | null;
  dueDate: string | null;
  closedAt: string | null;
  createdAt: string;
  client?: { id: string; nameAr: string } | null;
  service: { id: string; name: string; code: string; slaDays: number };
  members: { userId: string; role: string; allocationPct: number; user: { id: string; name: string } }[];
  tasksTotal?: number;
  tasksDone?: number;
}

function normalizeEngagement(e: RawEngagement): BoardEngagement {
  return {
    id: e.id,
    code: e.code,
    title: e.title,
    status: e.status,
    periodYear: e.periodYear,
    periodMonth: e.periodMonth,
    clientId: e.clientId,
    clientName: e.client?.nameAr ?? null,
    service: { id: e.service.id, name: e.service.name, code: e.service.code, slaDays: e.service.slaDays, defaultFee: 0 },
    feeAmount: e.feeAmount,
    currency: e.currency,
    startDate: e.startDate,
    dueDate: e.dueDate,
    closedAt: e.closedAt,
    members: e.members.map((m) => ({ userId: m.userId, name: m.user.name, role: m.role, allocationPct: m.allocationPct })),
    tasksTotal: e.tasksTotal ?? 0,
    tasksDone: e.tasksDone ?? 0,
    createdAt: e.createdAt,
  };
}

export function EngagementsBoard({
  initialEngagements,
  clients,
  services,
  users,
  userRole,
}: {
  initialEngagements: BoardEngagement[];
  clients: { id: string; nameAr: string }[];
  services: { id: string; name: string; code: string; slaDays: number; defaultFee: number; billingType: string }[];
  users: { id: string; name: string }[];
  userRole: string;
}) {
  const router = useRouter();
  const [rows, setRows] = useState<BoardEngagement[]>(initialEngagements);
  const [fStatus, setFStatus] = useState("");

  // إنشاء
  const [createOpen, setCreateOpen] = useState(false);
  const [clientId, setClientId] = useState("");
  const [serviceId, setServiceId] = useState("");
  const [periodYear, setPeriodYear] = useState(String(new Date().getFullYear()));
  const [periodMonth, setPeriodMonth] = useState("0");
  const [title, setTitle] = useState("");
  const [titleTouched, setTitleTouched] = useState(false);
  const [fee, setFee] = useState("");
  const [feeTouched, setFeeTouched] = useState(false);
  const [memberRows, setMemberRows] = useState<MemberRow[]>([]);
  const [submitting, setSubmitting] = useState(false);

  // تفاصيل
  const [detailId, setDetailId] = useState<string | null>(null);
  const [detail, setDetail] = useState<DetailData | null>(null);

  const filtered = rows.filter((r) => !fStatus || r.status === fStatus);

  // ملف حديث لم تولد مهامه بعد → الطابور لم يعمل: نوقظ الدورة حتى تكتمل التوليد
  const needsGeneration = rows.some(
    (r) => r.tasksTotal === 0 && r.status !== "CLOSED" && Date.now() - new Date(r.createdAt).getTime() < 5 * 60 * 1000
  );

  const refresh = useCallback(async () => {
    if (needsGeneration) await apiFetch("/api/automation/tick", { method: "POST", silent: true });
    const res = await apiFetch<RawEngagement[]>("/api/engagements", { silent: true });
    if (res.ok && Array.isArray(res.data)) setRows(res.data.map(normalizeEngagement));
    router.refresh();
  }, [needsGeneration, router]);

  useEffect(() => {
    if (!needsGeneration) return;
    const t = setInterval(() => {
      refresh().catch(() => {});
    }, 8000);
    return () => clearInterval(t);
  }, [needsGeneration, refresh]);

  const service = services.find((s) => s.id === serviceId);

  // اقتراح تلقائي للعنوان والأجر عند اختيار العميل/الخدمة (يُتخطى إن كتب المستخدم)
  useEffect(() => {
    const client = clients.find((c) => c.id === clientId);
    if (!titleTouched && client && service) {
      const m = Number(periodMonth);
      setTitle(`${client.nameAr} — ${service.name} ${periodYear}${m ? " " + (MONTHS[m - 1] ?? "") : ""}`);
    }
  }, [clientId, serviceId, periodYear, periodMonth, clients, service, titleTouched]);

  useEffect(() => {
    if (!feeTouched && service) setFee(service.defaultFee ? String(service.defaultFee) : "");
  }, [serviceId, service, feeTouched]);

  const duePreview = (() => {
    if (!service) return null;
    const y = Number(periodYear);
    const m = Number(periodMonth) || 1;
    return new Date(Date.UTC(y, m - 1, 1, 0, 0, 0, 0).getTime() + service.slaDays * 86400000);
  })();

  const create = async () => {
    if (!clientId || !serviceId) {
      toast.error("اختر العميل والخدمة");
      return;
    }
    if (!title.trim()) {
      toast.error("العنوان مطلوب");
      return;
    }
    setSubmitting(true);
    const body = {
      clientId,
      serviceId,
      periodYear: Number(periodYear),
      periodMonth: Number(periodMonth) || null,
      title: title.trim(),
      feeAmount: fee ? Number(fee) : 0,
      dueDate: duePreview ? duePreview.toISOString() : undefined,
      members: memberRows.filter((r) => r.userId).map((r) => ({ userId: r.userId, role: r.role, allocationPct: r.allocationPct ? Number(r.allocationPct) : 0 })),
    };
    const res = await apiFetch(`/api/engagements`, { method: "POST", body: JSON.stringify(body), silent: true });
    setSubmitting(false);
    if (!res.ok) {
      toast.error(res.error ?? "تعذّر الإنشاء");
      return;
    }
    toast.success("أُنشئ ملف العمل — جارٍ توليد قائمة المهام آليًا");
    setCreateOpen(false);
    setClientId("");
    setServiceId("");
    setTitle("");
    setTitleTouched(false);
    setFee("");
    setFeeTouched(false);
    setMemberRows([]);
    await refresh();
  };

  const openDetail = async (id: string) => {
    setDetailId(id);
    setDetail(null);
    const res = await apiFetch<RawDetail>(`/api/engagements/${id}`, { silent: true });
    if (res.ok && res.data) {
      setDetail({
        ...res.data,
        members: res.data.members.map((m) => ({ name: m.user.name, role: m.role, allocationPct: m.allocationPct })),
      });
    }
  };

  const closeEngagement = async (id: string, code: string) => {
    if (!window.confirm(`إغلاق الملف ${code}؟ لن يمكن إضافة مهام جديدة بعده.`)) return;
    const res = await apiFetch(`/api/engagements/${id}`, { method: "PUT", body: JSON.stringify({ status: "CLOSED" }), silent: true });
    if (res.ok) {
      toast.success("أُغلق الملف");
      await refresh();
    } else {
      toast.error(res.error ?? "تعذّر الإغلاق");
    }
  };

  const remove = async (id: string, code: string) => {
    if (!window.confirm(`حذف الملف ${code} نهائيًا؟ مهامه ستبقى في شاشة المهام بدون ملف.`)) return;
    const res = await apiFetch(`/api/engagements/${id}`, { method: "DELETE", silent: true });
    if (res.ok) {
      toast.success("حُذف الملف");
      setDetailId(null);
      await refresh();
    } else {
      toast.error(res.error ?? "تعذّر الحذف");
    }
  };

  const addMemberRow = () => setMemberRows((prev) => [...prev, { userId: "", role: "MEMBER", allocationPct: "" }]);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2">
        <Button onClick={() => setCreateOpen(true)}>
          <Plus className="size-4" />
          ملف عمل جديد
        </Button>
        <Select value={fStatus || "all"} onValueChange={(v) => setFStatus(v === "all" ? "" : v)}>
          <SelectTrigger className="w-44">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">كل الحالات</SelectItem>
            {Object.entries(ENGAGEMENT_STATUS_LABELS).map(([v, l]) => (
              <SelectItem key={v} value={v}>
                {l}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Button variant="outline" size="sm" onClick={() => refresh().catch(() => {})}>
          <Loader2 className="size-4" />
          تحديث
        </Button>
      </div>

      {filtered.length === 0 && (
        <Card>
          <CardContent className="flex flex-col items-center gap-2 py-10 text-center text-muted-foreground">
            <Briefcase className="size-8" />
            <p>لا توجد ملفات عمل بعد — أنشئ أول ملف وستُولد قائمة مهامه آليًا</p>
          </CardContent>
        </Card>
      )}

      {filtered.map((e) => {
        const days = daysUntil(e.dueDate);
        return (
          <Card key={e.id} className="transition-colors hover:bg-accent/30">
            <CardContent className="flex flex-wrap items-center gap-3 py-3.5">
              <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-secondary">
                <Briefcase className="size-5 text-muted-foreground" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono text-xs text-muted-foreground">{e.code}</span>
                  <span className="truncate font-medium">{e.title}</span>
                  <Badge variant={STATUS_VARIANT[e.status] ?? "secondary"}>{ENGAGEMENT_STATUS_LABELS[e.status] ?? e.status}</Badge>
                </div>
                <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground">
                  <span>{e.clientName ?? "—"}</span>
                  <span>{e.service.name}</span>
                  <span>{periodLabel(e.periodYear, e.periodMonth)}</span>
                  {e.dueDate && e.status !== "CLOSED" && days !== null && (
                    <span className={days < 0 ? "font-medium text-destructive" : days <= 3 ? "font-medium text-warning" : ""}>
                      {days < 0 ? `متأخر ${Math.abs(days)} يوم` : `يستحق خلال ${days} يوم`}
                    </span>
                  )}
                  {e.tasksTotal > 0 && (
                    <span>
                      المهام: {e.tasksDone}/{e.tasksTotal}
                    </span>
                  )}
                  {e.tasksTotal === 0 && e.status !== "CLOSED" && Date.now() - new Date(e.createdAt).getTime() < 5 * 60 * 1000 && (
                    <span className="text-primary">جارٍ توليد المهام…</span>
                  )}
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <div className="flex -space-x-2">
                  {e.members.slice(0, 4).map((m) => (
                    <span
                      key={m.userId}
                      title={`${m.name} — ${MEMBER_ROLE_LABELS[m.role] ?? m.role}`}
                      className="flex size-7 items-center justify-center rounded-full border-2 border-card bg-secondary text-[10px] font-bold"
                    >
                      {initials(m.name)}
                    </span>
                  ))}
                </div>
                <Button size="sm" variant="outline" onClick={() => openDetail(e.id)}>
                  <Eye className="size-4" />
                  التفاصيل
                </Button>
                {e.status !== "CLOSED" && (
                  <Button size="sm" variant="ghost" onClick={() => closeEngagement(e.id, e.code)}>
                    <CheckCircle2 className="size-4" />
                    إغلاق
                  </Button>
                )}
                {userRole === "admin" && e.status === "CLOSED" && (
                  <Button size="sm" variant="ghost" className="text-destructive" onClick={() => remove(e.id, e.code)}>
                    <Trash2 className="size-4" />
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        );
      })}

      {/* إنشاء ملف عمل */}
      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>ملف عمل جديد</DialogTitle>
            <DialogDescription>
              عند الحفظ تُنشئ الأتمتة قائمة المهام من قوالب الخدمة، بتواريخ محسوبة من بداية الفترة وإزاحة كل قالب.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="flex flex-col gap-1.5">
              <Label>العميل</Label>
              <Select value={clientId || "none"} onValueChange={(v) => setClientId(v === "none" ? "" : v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">اختر العميل…</SelectItem>
                  {clients.map((c) => (
                    <SelectItem key={c.id} value={c.id}>
                      {c.nameAr}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label>الخدمة</Label>
              <Select value={serviceId || "none"} onValueChange={(v) => setServiceId(v === "none" ? "" : v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">اختر الخدمة…</SelectItem>
                  {services.map((s) => (
                    <SelectItem key={s.id} value={s.id}>
                      {s.name} — SLA {s.slaDays} يوم
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label>سنة الفترة</Label>
              <Input type="number" value={periodYear} min={2000} max={2100} onChange={(e) => setPeriodYear(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label>شهر الفترة</Label>
              <Select value={periodMonth} onValueChange={setPeriodMonth}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="0">السنة كاملة</SelectItem>
                  {MONTHS.map((m, i) => (
                    <SelectItem key={m} value={String(i + 1)}>
                      {m}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5 sm:col-span-2">
              <Label>العنوان</Label>
              <Input value={title} onChange={(e) => { setTitle(e.target.value); setTitleTouched(true); }} placeholder="يُقترح تلقائيًا من العميل والخدمة" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label>أجر الملف ({services.find((s) => s.id === serviceId)?.billingType === "HOURLY" ? "ساعي" : "ثابت"})</Label>
              <Input type="number" min={0} value={fee} onChange={(e) => { setFee(e.target.value); setFeeTouched(true); }} placeholder="0" />
            </div>
            {duePreview && (
              <div className="flex items-end pb-1.5 text-xs text-muted-foreground">
                <span>
                  موعد الاستحقاق المقترح: {duePreview.toLocaleDateString("ar-EG")} (بداية الفترة + SLA {service?.slaDays} يوم)
                </span>
              </div>
            )}
          </div>

          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between">
              <Label>الطاقم</Label>
              <Button type="button" variant="outline" size="sm" onClick={addMemberRow}>
                <Plus className="size-3.5" />
                إضافة عضو
              </Button>
            </div>
            {memberRows.length === 0 && <p className="text-xs text-muted-foreground">يمكنك إضافة الطاقم الآن أو لاحقًا من التفاصيل.</p>}
            {memberRows.map((row, i) => (
              <div key={i} className="flex items-center gap-2">
                <Select value={row.userId || "none"} onValueChange={(v) => setMemberRows((prev) => prev.map((r, j) => (j === i ? { ...r, userId: v === "none" ? "" : v } : r)))}>
                  <SelectTrigger className="flex-1">
                    <SelectValue placeholder="اختر العضو…" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">اختر…</SelectItem>
                    {users.map((u) => (
                      <SelectItem key={u.id} value={u.id}>
                        {u.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Select value={row.role} onValueChange={(v) => setMemberRows((prev) => prev.map((r, j) => (j === i ? { ...r, role: v as MemberRow["role"] } : r)))}>
                  <SelectTrigger className="w-36">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.entries(MEMBER_ROLE_LABELS).map(([v, l]) => (
                      <SelectItem key={v} value={v}>
                        {l}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Input type="number" min={0} max={100} placeholder="%" className="w-20" value={row.allocationPct} onChange={(e) => setMemberRows((prev) => prev.map((r, j) => (j === i ? { ...r, allocationPct: e.target.value } : r)))} />
                <Button type="button" variant="ghost" size="icon" onClick={() => setMemberRows((prev) => prev.filter((_, j) => j !== i))}>
                  <X className="size-4" />
                </Button>
              </div>
            ))}
          </div>
          <DialogFooter>
            <Button onClick={create} disabled={submitting}>
              {submitting ? <Loader2 className="size-4 animate-spin" /> : <Briefcase className="size-4" />}
              إنشاء الملف وتوليد المهام
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* تفاصيل ملف */}
      <Dialog open={detailId !== null} onOpenChange={(o) => !o && setDetailId(null)}>
        <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl">
          <DialogHeader>
            <DialogTitle>تفاصيل ملف العمل</DialogTitle>
            {detail && (
              <DialogDescription>
                {detail.code} — {detail.client?.nameAr ?? ""} · {detail.service.name} · SLA {detail.service.slaDays} يوم
              </DialogDescription>
            )}
          </DialogHeader>
          {!detail && <Loader2 className="size-6 animate-spin text-muted-foreground" />}
          {detail && (
            <div className="flex flex-col gap-5">
              <div className="grid gap-2 text-sm sm:grid-cols-2">
                <div>
                  <span className="text-muted-foreground">الحالة: </span>
                  <Badge variant={STATUS_VARIANT[detail.status] ?? "secondary"}>{ENGAGEMENT_STATUS_LABELS[detail.status] ?? detail.status}</Badge>
                </div>
                {detail.dueDate && (
                  <div>
                    <span className="text-muted-foreground">الاستحقاق: </span>
                    {new Date(detail.dueDate).toLocaleDateString("ar-EG")}
                  </div>
                )}
                {detail.notes && (
                  <div className="sm:col-span-2">
                    <span className="text-muted-foreground">ملاحظات: </span>
                    {detail.notes}
                  </div>
                )}
              </div>

              <div>
                <h4 className="mb-2 flex items-center gap-1.5 text-sm font-semibold">
                  <UserRound className="size-4" />
                  الطاقم
                </h4>
                {detail.members.length === 0 && <p className="text-xs text-muted-foreground">لم يُسند بعد — أضيف أعضاء من شاشة إنشاء الملف عند التعديل.</p>}
                <div className="flex flex-col gap-1.5">
                  {detail.members.map((m, i) => (
                    <div key={i} className="flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm">
                      <span>{m.name}</span>
                      <Badge variant={ROLE_VARIANT[m.role] ?? "muted"}>{MEMBER_ROLE_LABELS[m.role] ?? m.role}</Badge>
                      {m.allocationPct > 0 && <span className="text-xs text-muted-foreground">{m.allocationPct}%</span>}
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <h4 className="mb-2 text-sm font-semibold">المهام المولّدة ({detail.tasks.length})</h4>
                {detail.tasks.length === 0 && <p className="text-xs text-muted-foreground">لم تولَّد بعد — ستظهر هنا خلال ثوانٍ بعد إنشاء الملف.</p>}
                <div className="flex flex-col gap-1.5">
                  {detail.tasks.map((t) => (
                    <div key={t.id} className="flex flex-wrap items-center gap-2 rounded-md border px-3 py-1.5 text-sm">
                      <span className="min-w-0 flex-1 truncate">{t.title}</span>
                      {t.autoGenerated && <Badge variant="info">آلي</Badge>}
                      <span className="text-xs text-muted-foreground">{new Date(t.dueDate).toLocaleDateString("ar-EG")}</span>
                      {t.assignedToUser && <span className="text-xs text-muted-foreground">{t.assignedToUser.name}</span>}
                      <Badge variant={t.status === "DONE" ? "success" : t.status === "TODO" ? "secondary" : "warning"}>{t.status}</Badge>
                    </div>
                  ))}
                </div>
              </div>

              {detail.documents.length > 0 && (
                <div>
                  <h4 className="mb-2 text-sm font-semibold">الوثائق المرتبطة ({detail.documents.length})</h4>
                  <div className="flex flex-wrap gap-1.5">
                    {detail.documents.map((d, i) => (
                      <Badge key={i} variant="muted">
                        {d.title}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
          <DialogFooter className="gap-2 sm:justify-between">
            {detail && detail.status !== "CLOSED" && (
              <Button
                variant="outline"
                onClick={async () => {
                  if (!detailId) return;
                  const res = await apiFetch(`/api/engagements/${detailId}`, { method: "PUT", body: JSON.stringify({ status: "CLOSED" }), silent: true });
                  if (res.ok) {
                    toast.success("أُغلق الملف");
                    setDetailId(null);
                    await refresh();
                  } else toast.error(res.error ?? "تعذّر الإغلاق");
                }}
              >
                <XCircle className="size-4" />
                إغلاق الملف
              </Button>
            )}
            {detail && userRole === "admin" && detail.status === "CLOSED" && (
              <Button variant="destructive" onClick={() => detailId && remove(detailId, detail.code)}>
                <Trash2 className="size-4" />
                حذف
              </Button>
            )}
            <Button variant="ghost" onClick={() => setDetailId(null)}>
              إغلاق
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
